### ISSUE TITLE
mobile phone paynows not working

### ISSUE THREAD

**Issue by noxqs** [daffodilistic/pyPayNowSg#1]
You hardcode the proxy type to 2 (UEN) which makes payNow by mobilephone impossible.
Change line 95 in PayNowConfigFactory.py to:
`            (PayNowMerchantAccountInfo.PROXY_TYPE, proxy_type),`

Then mobilephone paynows also work !

**Comment by daffodilistic** [comment]
Hey thanks for reporting!

Unfortunately I don't have time to fix this in the next few weeks; will look into this in mid November.

**Comment by daffodilistic** [comment]
Fixed in [0.8.1](https://github.com/daffodilistic/pyPayNowSg/releases/tag/0.8.1) @ https://github.com/daffodilistic/pyPayNowSg/commit/b2965c462971c344bed422c8e89b74b8100657e0
